### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by ivansamchuk** [ivansamchuk/homepage#6]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by samchuk17** [comment]
- 5+ years of experience as Software Tester;
- 2 years of experience as automation QA (Python, RobotFramework);
- Responsible, goal-oriented, communicable, able to learn new technologies

**Comment by samchuk17** [comment]
<h2>Résumé</h2> 
<p>&mdash; Proficient in software development life cycle including test strategy preparation, test plan development, test case creation, test execution and bug tracking. Tested applications in Agile development processes. Analyzed business requirements, software requirement specifications to create a test plan and test case for manual and automated testing. Experienced in different types of testing, for example, black box testing, white box testing, functional, GUI testing, regression, integration, and performance testing. Understanding of Quality Assurance Life Cycle and Software Development Life Cycle. Developed and maintained automated test scripts and environment. Enjoy learning new tools and technologies. </p>
