### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by ivansamchuk** [ivansamchuk/homepage#8]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by samchuk17** [comment]
<ul>
  <li>
    <p><small>June 2014 – March 2015</small></p>
    <p>JoyRocks (F2P Games Company)
      Project: Birds Town
      Position: Junior QC Engineer
      Responsibilities:
      Execute different testing types: cross browser testing, exploratory testing, functional testing and regression testing;
      Design and update test documentation;
      Defect tracking.
    </p>
  </li>
  <li>
    <p><small>May 2015 – August 2017</small></p>
    <p>Ninja505 (F2P Games Company)
      Project: F2P game Woolly Valley 
      Position: QC Engineer, Game Designer, Games Analyst
      Responsibilities:
      Bugs tracking;
      Writing / Executing test-cases;
      Describing game mechanics and new functionality;
      Analyzing game metrics, players activity. Writing reports and making conclusions.
    </p>
  </li>
  <li>
    <p><small>October 2017 – Present</small></p>
    <p>Renome-Smart
      Position: QA Engineer, QA Automaton Engineer (RobotFramework)
      Responsibilities:
      Bugs tracking;
      Writing / Executing test-cases;
      Writing automated tests
      Creating test reports
    </p>
  </li>
</ul>
