### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by ivansamchuk** [ivansamchuk/homepage#9]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by samchuk17** [comment]
PERSONALITY
- COMMON SENSE
- RESTRAINED
- PERSISTENT
- CONFIDENT
- DREAMER
- OBSERVANT
- INVENTIVE
- CURIOUS

LIKE 😃
EVENTS, HUMOR, PATIENCE, SOMETIMES SILENCE, SOMETIMES NOISE, BIKES, EQUIPMENT, CATS, CYBERPUNK, INTERESTING BOOKS, MOVIES, SERIALS.

DISLIKE 😞
ALCOHOL, DEGRADING, PEOPLE BATTERING YOURSELF PRICE, TELEVISION, CONVERSATIONS WITH NO SENSE, ENVY, COMPARISON WITH OTHERS.

DESIRES 🥺
TO BE HEALTHY ● TO BE SIGNIFICANT ● TO BE EFFECTIVE  ● WORK CORRECTLY ● DO NOT BE AFRAID TO LOOK FOOLISH ● BECOMING ONLY BETTER PERSON ● BE HAPPY
